# Docker-compose file for an End-to-End demo
# Missing here: the device connecting to iotagent-ul.

version: '3'

services:

  orion:
    image: fiware/orion:1.7.0
    ports:
      - "1026:1026"
    command: -dbhost mongo

  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"

  cratedb:
    image: crate
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      - "4300:4300"
    command: -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=crate-datasource,grafana-clock-panel,grafana-worldmap-panel
    depends_on:
      - cratedb
